name: registry-hedgehog-aeson
version: 0.2.0.0
synopsis: Hedgehog generators for Aeson

description: This library provides generators for Aeson values which can be easily customized.

category: Test

license: MIT
license-file: LICENSE.txt

maintainer: etorreborre@yahoo.com
git: https://github.com/etorreborre/registry-hedgehog-aeson

ghc-options:
  -Wall
  -Wcompat
  -Wincomplete-record-updates
  -fhide-source-paths
  -fprint-potential-instances
  -fno-warn-partial-type-signatures
  -optP-Wno-nonportable-include-path

default-extensions:
 - BangPatterns
 - DefaultSignatures
 - EmptyCase
 - ExistentialQuantification
 - FlexibleContexts
 - FlexibleInstances
 - FunctionalDependencies
 - GADTs
 - GeneralizedNewtypeDeriving
 - InstanceSigs
 - KindSignatures
 - LambdaCase
 - MultiParamTypeClasses
 - MultiWayIf
 - NamedFieldPuns
 - NoImplicitPrelude
 - OverloadedStrings
 - PatternSynonyms
 - Rank2Types
 - RankNTypes
 - ScopedTypeVariables
 - StandaloneDeriving
 - TupleSections
 - TypeApplications
 - TypeFamilies
 - TypeFamilyDependencies
 - TypeOperators

dependencies:
  - aeson                >= 1.0   && < 3
  - base                 >= 4.7   && < 5
  - containers           >= 0.2   && < 1
  - hedgehog             >= 1.0   && < 2
  - mmorph               >= 1     && < 2
  - multimap             >= 1     && < 2
  - protolude            >= 0.3   && < 0.4
  - registry             >= 0.3   && < 1
  - scientific           >= 0.3   && < 0.4
  - tasty                >= 1     && < 2
  - tasty-discover       >= 2     && < 5
  - tasty-hedgehog       >= 1.0   && < 2.0
  - tasty-th             >= 0.1   && < 1
  - template-haskell     >= 2.13  && < 3.0
  - text                 >= 1     && < 2
  - transformers         >= 0.5   && < 2
  - universum            >= 1     && < 2
  - unordered-containers >= 0.1   && < 1
  - vector               >= 0.1   && < 1

library:
  source-dirs: src

  ghc-options:
    -Wincomplete-uni-patterns

tests:
  spec:
    main: test.hs
    source-dirs:
      - test
    dependencies:
      - registry-hedgehog
      - registry-hedgehog-aeson

    ghc-options:
      -threaded
      -rtsopts
      -with-rtsopts=-N
      -fno-warn-orphans
      -fno-warn-missing-signatures
      -fno-warn-incomplete-uni-patterns
      -fno-warn-type-defaults
      -optP-Wno-nonportable-include-path
